### ISSUE TITLE
Postgres database not recreated

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store-benchmarks#5]
We can not delete a used database in postgres and we can not select a database. The following statements produces errors for postgres (Postgres logs):

```
$connection->exec("DROP DATABASE IF EXISTS $
$connection->exec("CREATE DATABASE $
$connection->exec("use $dbName");
```

We have to close the active connection, drop the database with another connection which uses the `postgres` or any other database and then create the benchmark database again and use a new connection with the benchmark database.

**Comment by prolic** [comment]
`use $dbName` is wrong for postgres. Use this instead: `\c $dbName`

**Comment by sandrokeil** [comment]
@prolic This doesn't work with PDO.

```
ERROR:  syntax error at or near "\" at character 1
STATEMENT:  \c postgres
```

**Comment by prolic** [comment]
ok will check later
